def on_forever():
    music.set_volume(50)
    if input.is_gesture(Gesture.TILT_LEFT):
        music.stop_all_sounds()
        basic.show_string("1")
        basic.pause(2000)
        basic.clear_screen()
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(698, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.HALF))
        music.play_tone(440, music.beat(BeatFraction.WHOLE))
        music.play_tone(440, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(523, music.beat(BeatFraction.HALF))
        music.play_tone(494, music.beat(BeatFraction.HALF))
        music.play_tone(494, music.beat(BeatFraction.HALF))
        music.play_tone(494, music.beat(BeatFraction.HALF))
        music.play_tone(659, music.beat(BeatFraction.WHOLE))
        music.play_tone(587, music.beat(BeatFraction.WHOLE))
        music.play_tone(523, music.beat(BeatFraction.BREVE))
        if input.button_is_pressed(Button.A):
            music.set_volume(music.volume() - 1)
            basic.show_number(music.volume())
        if input.button_is_pressed(Button.B):
            music.set_volume(music.volume() + 1)
            basic.show_number(music.volume())
    if input.is_gesture(Gesture.TILT_RIGHT):
        music.stop_all_sounds()
        music._play_default_background(music.built_in_playable_melody(Melodies.CHASE),
            music.PlaybackMode.IN_BACKGROUND)
        basic.show_string("2")
        if input.button_is_pressed(Button.A):
            music.set_volume(music.volume() - 1)
            basic.show_number(music.volume())
        if input.button_is_pressed(Button.B):
            music.set_volume(music.volume() + 1)
            basic.show_number(music.volume())
    if input.button_is_pressed(Button.A):
        music.set_volume(music.volume() - 1)
        basic.show_number(music.volume())
    if input.button_is_pressed(Button.B):
        music.set_volume(music.volume() + 1)
        basic.show_number(music.volume())
basic.forever(on_forever)
